task:
  labels:
  - H
  - L
  cls_type: HL
  num_of_dim: 2
midi:
  feature_path: ../dataset/remi+
  pad_idx: 1359
hparams:
  dataset: EMOPIA
  midi: remi+
  task: h_l
  r: 14
  lstm_hidden_dim: 128
  embedding_size: 300
  batch_size: 1
  num_workers: 1
  lr: 0.001
  weight_decay: 0.0001
  T_0: 45
  max_epochs: 1
  gpus: 0
  distributed_backend: dp
  deterministic: true
  benchmark: false
  reproduce: true
